### ISSUE TITLE
Logging Clipboard error

### ISSUE THREAD

**Issue by kaobajagi** [xp4xbox/Puffader#38]
OS: Windows

This error occurred when running the .exe after compilation during testing.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "Puffader.py", line 106, in MonitorClipboard
TypeError: Specified clipboard format is not available

**Comment by xp4xbox** [comment]
Probably because of copying a picture or a file.
