### ISSUE TITLE
some error screen log

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#41]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 1073, in run
  File "svchost.py", line 224, in TakeScr
  File "pyscreeze\__init__.pyc", line 312, in _screenshot_win32
  File "PIL\ImageGrab.pyc", line 41, in grab
IOError: screen grab failed

Exception in thread Thread-16:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "svchost.py", line 215, in SendScreen
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\home\\AppData\\Local\\Temp/20180212144502.png'

Exception in thread Thread-27:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "svchost.py", line 215, in SendScreen
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\home\\AppData\\Local\\Temp/20180212144655.png'

Exception in thread Thread-40:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "svchost.py", line 215, in SendScreen
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\home\\AppData\\Local\\Temp/20180212144756.png'

Exception in thread Thread-55:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "svchost.py", line 215, in SendScreen
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\home\\AppData\\Local\\Temp/20180212145612.png'

Regards

**Comment by xp4xbox** [comment]
Does this still happen? I think what happened is that the screenshot could not be taken for some reason.

**Comment by xp4xbox** [comment]
@tehseensagar If not, I will close the issue as I think this was just a one-time bug.
